export const SHOW_BOOKS_BASKET_CONTAINER = "SHOW_BOOKS_BASKET_CONTAINER";
export const BOOKS_BASKET_LIST_CHANGE = "BOOKS_BASKET_LIST_CHANGE";
export const SET_BOOKS_LIST = "SET_BOOKS_LIST";
export const SAVE_USERS_LIST = "SAVE_USERS_LIST";
export const SAVE_RESERVATIONS_LIST = "SAVE_RESERVATIONS_LIST";
export const SAVE_ADMINS_LIST = "SAVE_ADMINS_LIST";
export const BOOK_CREATION_REQUESTS_LIST = "BOOK_CREATION_REQUESTS_LIST";
