export const SHOW_BOOKS_BASKET_CONTAINER = "SHOW_BOOKS_BASKET_CONTAINER";
export const BOOKS_BASKET_LIST_CHANGE = "BOOKS_BASKET_LIST_CHANGE";
export const SET_BOOKS_LIST = "SET_BOOKS_LIST";
export const SAVE_USERS_LIST = "SAVE_USERS_LIST";
